<?php

namespace Tests\Feature;

use App\Models\Photo;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class PhotosTest extends TestCase
{

    use RefreshDatabase;

    private $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create([
            'balance' => 30000
        ]);
    }

    private function seedPhotos()
    {
        $users = User::factory(10)->create();
        foreach($users as $user) {
            Photo::factory(4)->create(['user_id'=> $user->id, 'artist_id' => $user->id]);
        }
    }
    public function test_user_cant_see_edit_button_on_other_users_photos()
    {
        $this->seedPhotos();
        $response = $this->actingAs($this->user)->get('/photos');
        $response->assertDontSee('EDIT');
    }

    public function test_user_cant_edit_other_users_photos()
    {
        $this->seedPhotos();
        $response = $this->actingAs($this->user)->get('photos/20/edit');
        $response->assertStatus(403);
    }

    public function test_user_can_create_new_photo()
    {
        $response = $this->actingAs($this->user)->get('photos/create');
        $response->assertStatus(200);
        $response->assertSee('Save');
    }

    public function test_user_can_see_buy_button_on_photos()
    {
        $this->seedPhotos();
        $response = $this->actingAs($this->user)->get('photos');
        $response->assertStatus(200);
        $response->assertSee('Buy');
    }

    public function test_user_cant_buy_without_balance()
    {
        $this->seedPhotos();
        $photo = Photo::create([
            'user_id' => 10,
            'artist_id' => 10,
            'price' => 301000,
            'title' => 'Most Expensive Photo',
            'description' => 'Here you see the most expensive photo, that you can not afford',
            'path' => 'storage/photos/seeds/pedroOne.jpg',
            'original_name' => 'pedroOne.jpg'
        ]);

        $response = $this->actingAs($this->user)->get('photos/buy/' . $photo->id);
        $response->assertSessionHasErrors();
    }

    public function test_user_can_buy_with_balance()
    {
        $this->seedPhotos();
        $photo = Photo::create([
            'user_id' => 10,
            'artist_id' => 10,
            'price' => 1000,
            'title' => 'Most Expensive Photo',
            'description' => 'Here you see the most expensive photo, that you can not afford',
            'path' => 'storage/photos/seeds/pedroOne.jpg',
            'original_name' => 'pedroOne.jpg'
        ]);

        $response = $this->actingAs($this->user)->get('photos/buy/' . $photo->id);
        $response->assertRedirect('/');
        $response->assertSessionHasNoErrors();
        $this->followRedirects($response)->assertSee("Bought");
    }

}
